tests

diff --git a/.github/workflows/dapr-test.yml b/.github/workflows/dapr-test.yml
--- a/.github/workflows/dapr-test.yml
+++ b/.github/workflows/dapr-test.yml
@@ -22,6 +22,9 @@
 name: dapr-test
 
 on:
+  # Run every 2 hours
+  schedule:
+    - cron: '0 */2 * * *'
   # Manual trigger
   workflow_dispatch:
   # Dispatch on external events
@@ -49,11 +52,13 @@ env:
   AZURE_ARM_REGIONS: "eastus"
   # Container registry where to cache e2e test images
   DAPR_CACHE_REGISTRY: "dapre2eacr.azurecr.io"
+  # Whether to collect TCP dumps
+  TCP_DUMPS: false
 
 jobs:
   deploy-infrastructure:
     name: Deploy test infrastructure
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-22.04
     steps:
       - name: Set up for scheduled test
         if: github.event_name != 'repository_dispatch'
@@ -63,7 +68,7 @@ jobs:
         shell: bash
       - name: Parse test payload
         if: github.event_name == 'repository_dispatch'
-        uses: actions/github-script@0.3.0
+        uses: actions/github-script@v6.2.0
         with:
           github-token: ${{secrets.DAPR_BOT_TOKEN}}
           script: |
@@ -73,8 +78,25 @@ jobs:
               // Set environment variables
               fs.appendFileSync(process.env.GITHUB_ENV,
                 `CHECKOUT_REPO=${testPayload.pull_head_repo}\n`+
-                `CHECKOUT_REF=${testPayload.pull_head_ref}`);
+                `CHECKOUT_REF=${testPayload.pull_head_ref}\n`+
+                `PR_NUMBER=${testPayload.issue.number}`
+              );
             }
+      - name: Create PR comment
+        if: env.PR_NUMBER != ''
+        uses: marocchino/sticky-pull-request-comment@v2.2.0
+        with:
+          header: ${{ github.run_id }}
+          number: ${{ env.PR_NUMBER }}
+          hide: true
+          hide_classify: OUTDATED
+          GITHUB_TOKEN: ${{ secrets.DAPR_BOT_TOKEN }}
+          message: |
+            # Dapr E2E test
+
+            🔗 **[Link to Action run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})**
+
+            Commit ref: ${{ env.CHECKOUT_REF }}
       - name: Check out code
         if: env.CHECKOUT_REPO != ''
         uses: actions/checkout@v2
@@ -103,14 +125,17 @@ jobs:
           REGIONS_SIZE=${#REGIONS[@]}
           REGIONS_IDX=$(($RANDOM % $REGIONS_SIZE))
           REGION1=${REGIONS[$REGIONS_IDX]}
+          echo "REGION1=${REGION1}" >> $GITHUB_ENV
           REGION2=${REGIONS[$REGIONS_IDX]}
+          echo "REGION2=${REGION2}" >> $GITHUB_ENV
           REGION3=${{ env.AZURE_ARM_REGIONS }}
+          echo "REGION3=${REGION3}" >> $GITHUB_ENV
           echo "Deploying to Azure regions: Linux_amd64=${REGION1} Windows=${REGION2} Linux_arm64=${REGION3}"
           # Tags
           DATE_TAG=$(date --iso-8601=seconds)
           echo "Tags: date=${DATE_TAG}"
 
-          # Deploy both Linux and Windows cluster
+          # Deploy Linux arm64/amd64 and Windows clusters
           # Retry the deployment twice in case of transient failures (such as capacity constraints)
           success=false
           for i in 1 2 3; do 
@@ -124,10 +149,10 @@ jobs:
                 location2=${REGION2} \
                 location3=${REGION3} \
                 dateTag="${DATE_TAG}" \
-                diagLogAnalyticsWorkspaceResourceId="${{ secrets.AZURE_DIAG_LOG_ANALYTICS_WORKSPACE_ID }}" \
-                diagStorageResourceId="${{ secrets.AZURE_DIAG_STORAGE_ID }}" \
-                armDiagLogAnalyticsWorkspaceResourceId="${{ secrets.ARM_AZURE_DIAG_LOG_ANALYTICS_WORKSPACE_ID }}" \
-                armDiagStorageResourceId="${{ secrets.ARM_AZURE_DIAG_STORAGE_ID }}" \
+                diagLogAnalyticsWorkspaceResourceId="/subscriptions/07d1c04d-dba4-4685-912b-6f26e53b8401/resourcegroups/dapr-e2e-logs/providers/microsoft.operationalinsights/workspaces/dape2elogs41la" \
+                diagStorageResourceId="/subscriptions/07d1c04d-dba4-4685-912b-6f26e53b8401/resourceGroups/Dapr-E2E-Logs/providers/Microsoft.Storage/storageAccounts/dape2elogs41sa" \
+                armDiagLogAnalyticsWorkspaceResourceId="/subscriptions/07d1c04d-dba4-4685-912b-6f26e53b8401/resourcegroups/dapr-e2e-logs/providers/microsoft.operationalinsights/workspaces/dape2elogs41ala" \
+                armDiagStorageResourceId="/subscriptions/07d1c04d-dba4-4685-912b-6f26e53b8401/resourceGroups/Dapr-E2E-Logs/providers/Microsoft.Storage/storageAccounts/dape2elogs41asa" \
               && success=true \
               && break \
               || sleep 120
@@ -135,6 +160,40 @@ jobs:
           # Exit with error if failed
           $success || exit 1
         shell: bash
+      - name: Update PR comment for success
+        if: success() && env.PR_NUMBER != ''
+        uses: marocchino/sticky-pull-request-comment@v2.2.0
+        with:
+          header: ${{ github.run_id }}
+          number: ${{ env.PR_NUMBER }}
+          append: true
+          GITHUB_TOKEN: ${{ secrets.DAPR_BOT_TOKEN }}
+          message: |
+            ## ✅ Infrastructure deployed
+
+            | Cluster | Resource group name | Azure region |
+            | --- | --- | --- |
+            | Linux | `Dapr-E2E-${{ env.TEST_PREFIX }}l` | ${{ env.REGION1 }} |
+            | Windows | `Dapr-E2E-${{ env.TEST_PREFIX }}w` | ${{ env.REGION2 }} |
+            | Linux_arm64 | `Dapr-E2E-${{ env.TEST_PREFIX }}la` | ${{ env.REGION3 }} |
+      - name: Update PR comment for failure
+        if: failure() && env.PR_NUMBER != ''
+        uses: marocchino/sticky-pull-request-comment@v2.2.0
+        with:
+          header: ${{ github.run_id }}
+          number: ${{ env.PR_NUMBER }}
+          append: true
+          GITHUB_TOKEN: ${{ secrets.DAPR_BOT_TOKEN }}
+          message: |
+            ## ❌ Infrastructure deployment failed
+
+            | Cluster | Resource group name | Azure region |
+            | --- | --- | --- |
+            | Linux | `Dapr-E2E-${{ env.TEST_PREFIX }}l` | ${{ env.REGION1 }} |
+            | Windows | `Dapr-E2E-${{ env.TEST_PREFIX }}w` | ${{ env.REGION2 }} |
+            | Linux_arm64 | `Dapr-E2E-${{ env.TEST_PREFIX }}la` | ${{ env.REGION3 }} |
+
+            Please check the logs for details on the failure.
 
   build:
     name: Build for  ${{ matrix.target_os }} on ${{ matrix.target_arch }}
@@ -147,10 +206,10 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        os: [ubuntu-latest, windows-2019]
+        os: [ubuntu-22.04, windows-2019]
         target_arch: [amd64]
         include:
-          - os: ubuntu-latest
+          - os: ubuntu-22.04
             target_os: linux
           - os: windows-2019
             target_os: windows
@@ -166,7 +225,7 @@ jobs:
         shell: bash
       - name: Parse test payload
         if: github.event_name == 'repository_dispatch'
-        uses: actions/github-script@0.3.0
+        uses: actions/github-script@v6.2.0
         with:
           github-token: ${{secrets.DAPR_BOT_TOKEN}}
           script: |
@@ -176,7 +235,9 @@ jobs:
               // Set environment variables
               fs.appendFileSync(process.env.GITHUB_ENV,
                 `CHECKOUT_REPO=${testPayload.pull_head_repo}\n`+
-                `CHECKOUT_REF=${testPayload.pull_head_ref}`);
+                `CHECKOUT_REF=${testPayload.pull_head_ref}\n`+
+                `PR_NUMBER=${testPayload.issue.number}`
+              );
             }
       # In windows-2019 images, WSL comes with bash.exe (but no distribution) and that causes issues
       # See: https://github.community/t/wsl-not-available-for-hosted-windows-machine/124389
@@ -294,6 +355,31 @@ jobs:
         run: |
           make build-push-e2e-app-all
         shell: bash
+      - name: Update PR comment for success
+        if: success() && env.PR_NUMBER != ''
+        uses: marocchino/sticky-pull-request-comment@v2.2.0
+        with:
+          header: ${{ github.run_id }}
+          number: ${{ env.PR_NUMBER }}
+          append: true
+          GITHUB_TOKEN: ${{ secrets.DAPR_BOT_TOKEN }}
+          message: |
+            ## ✅ Build succeeded for ${{ matrix.target_os }}/${{ matrix.target_arch }}
+
+            - Image tag: `${{ env.DAPR_TAG }}`
+            - Test image tag: `${{ env.DAPR_TEST_TAG }}`
+      - name: Update PR comment for failure
+        if: failure() && env.PR_NUMBER != ''
+        uses: marocchino/sticky-pull-request-comment@v2.2.0
+        with:
+          header: ${{ github.run_id }}
+          number: ${{ env.PR_NUMBER }}
+          append: true
+          GITHUB_TOKEN: ${{ secrets.DAPR_BOT_TOKEN }}
+          message: |
+            ## ❌ Build failed for ${{ matrix.target_os }}/${{ matrix.target_arch }}
+
+            Please check the logs for details on the error.
 
   test-e2e:
     name: End-to-end ${{ matrix.target_os }} on ${{ matrix.target_arch }} tests
@@ -301,7 +387,7 @@ jobs:
       - build
       - deploy-infrastructure
     # Always run on Linux as the local OS is irrelevant and this is faster
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-22.04
     env:
       TARGET_OS: ${{ matrix.target_os }}
       TARGET_ARCH: ${{ matrix.target_arch }}
@@ -329,7 +415,7 @@ jobs:
         shell: bash
       - name: Parse test payload
         if: github.event_name == 'repository_dispatch'
-        uses: actions/github-script@0.3.0
+        uses: actions/github-script@v6.2.0
         with:
           github-token: ${{secrets.DAPR_BOT_TOKEN}}
           script: |
@@ -339,7 +425,9 @@ jobs:
               // Set environment variables
               fs.appendFileSync(process.env.GITHUB_ENV,
                 `CHECKOUT_REPO=${testPayload.pull_head_repo}\n`+
-                `CHECKOUT_REF=${testPayload.pull_head_ref}`);
+                `CHECKOUT_REF=${testPayload.pull_head_ref}\n`+
+                `PR_NUMBER=${testPayload.issue.number}`
+              );
             }
       - name: Set up Go ${{ env.GOVER }}
         if: env.CHECKOUT_REPO != ''
@@ -397,6 +485,7 @@ jobs:
           echo "TEST_RESOURCE_GROUP=Dapr-E2E-${TEST_PREFIX}" >> $GITHUB_ENV
         shell: bash
       - name: Enable tcpdump
+        if: env.TCP_DUMPS == 'true'
         run: |
           sudo tcpdump -nn -i any -w sntp.cap &
           sleep 1
@@ -445,7 +534,7 @@ jobs:
         run: |
           make save-dapr-control-plane-k8s-logs
       - name: Stop tcpdump
-        if: always()
+        if: always() && env.TCP_DUMPS == 'true'
         run: |
           sleep 1
           sudo kill -2 $(pgrep tcpdump)
@@ -454,12 +543,18 @@ jobs:
       - name: Compress logs
         if: always()
         run: |
-          gzip --fast -r ${{ env.DAPR_CONTAINER_LOG_PATH }}
-          gzip --fast -r ${{ env.DAPR_TEST_LOG_PATH }}
-          gzip --fast sntp.cap
+          test ${{ env.DAPR_CONTAINER_LOG_PATH }} \
+            && gzip --fast -r ${{ env.DAPR_CONTAINER_LOG_PATH }} \
+            || true
+          test ${{ env.DAPR_TEST_LOG_PATH }} \
+            && gzip --fast -r ${{ env.DAPR_TEST_LOG_PATH }} \
+            || true
+          test -f sntp.cap \
+            && gzip --fast sntp.cap \
+            || true
         shell: bash
       - name: Upload tcpdump
-        if: always()
+        if: always() && env.TCP_DUMPS == 'true'
         uses: actions/upload-artifact@master
         with:
           name: ${{ matrix.target_os }}_${{ matrix.target_arch }}_tcpdump
@@ -483,45 +578,47 @@ jobs:
           #TODO: .json suffix can be removed from artifact name after test analytics scripts are updated
           name: ${{ matrix.target_os }}_${{ matrix.target_arch }}_e2e.json
           path: ${{ env.TEST_OUTPUT_FILE_PREFIX }}_e2e.*
-      - name: Add test result comment to PR
-        if: always() && github.event_name == 'repository_dispatch' && env.TEST_PREFIX != ''
-        env:
-          JOB_CONTEXT: ${{ toJson(job) }}
-        uses: actions/github-script@0.3.0
+      - name: Update PR comment for success
+        if: success() && env.PR_NUMBER != ''
+        uses: marocchino/sticky-pull-request-comment@v2.2.0
         with:
-          github-token: ${{secrets.DAPR_BOT_TOKEN}}
-          script: |
-            const testPayload = context.payload.client_payload;
-            const jobContext = JSON.parse(process.env.JOB_CONTEXT);
-            const jobStatus = jobContext.status.toLowerCase();
-            const targetOs = process.env.TARGET_OS;
+          header: ${{ github.run_id }}
+          number: ${{ env.PR_NUMBER }}
+          append: true
+          GITHUB_TOKEN: ${{ secrets.DAPR_BOT_TOKEN }}
+          message: |
+            ## ✅ Tests succeeded on ${{ matrix.target_os }}/${{ matrix.target_arch }}
 
-            console.log(`Current Job Status: ${jobStatus}`);
+            - Image tag: `${{ env.DAPR_TAG }}`
+            - Test image tag: `${{ env.DAPR_TEST_TAG }}`
+      - name: Update PR comment for failure
+        if: failure() && env.PR_NUMBER != ''
+        uses: marocchino/sticky-pull-request-comment@v2.2.0
+        with:
+          header: ${{ github.run_id }}
+          number: ${{ env.PR_NUMBER }}
+          append: true
+          GITHUB_TOKEN: ${{ secrets.DAPR_BOT_TOKEN }}
+          message: |
+            ## ❌ Tests failed on ${{ matrix.target_os }}/${{ matrix.target_arch }}
 
-            var message = "";
+            Please check the logs for details on the error.
+      - name: Update PR comment for cancellation
+        if: cancelled() && env.PR_NUMBER != ''
+        uses: marocchino/sticky-pull-request-comment@v2.2.0
+        with:
+          header: ${{ github.run_id }}
+          number: ${{ env.PR_NUMBER }}
+          append: true
+          GITHUB_TOKEN: ${{ secrets.DAPR_BOT_TOKEN }}
+          message: |
+            ## ⚠️ Tests cancelled for ${{ matrix.target_os }}/${{ matrix.target_arch }}
 
-            const checkLink = `${process.env.GITHUB_SERVER_URL}/${process.env.GITHUB_REPOSITORY}/actions/runs/${process.env.GITHUB_RUN_ID}`;
-
-            if (jobStatus == "cancelled") {
-              message = `End-to-end tests cancelled on ${targetOs}. Please check the [build logs](${checkLink})`;
-            } else if (jobStatus == "success") {
-              message = `Congrats! All [end-to-end tests](${checkLink}) have passed on ${targetOs}. Thanks for your contribution!`;
-            } else if (jobStatus == "failure") {
-              message = `End-to-end tests failed on ${targetOs}. Please check the [build logs](${checkLink})`;
-            }
-
-            if (message) {
-              await github.issues.createComment({
-                owner: testPayload.issue.owner,
-                repo: testPayload.issue.repo,
-                issue_number: testPayload.issue.number,
-                body: message
-              });
-            }
+            The Action has been canceled
 
   cleanup:
     name: Clean up Azure resources
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-22.04
     needs:
       - test-e2e
     if: always()
